### ISSUE TITLE
issuee with the anndata object for the model dataset

### ISSUE THREAD

**Issue by deevdevil88** [metzakopian-lab/DNscRNAseq#2]
hi
Thank you adding the google drive links for the processed data. However, when i converted your Anndata object for the model dataset to a seurat or singlecellexperiment data, none of the metadata for the cells was transferred over. Is this because this info at the per cell level isnt stored in the object? I was wondering if you can include this per cell metadata for your object as well? it would really be handy as i wanted to use your dataset as a reference for annotating my own dataset but in seurat.

Best,
Devika

**Comment by pati-ni** [comment]
Hi Devika,
I have not yet found a reliable way to convert to seurat object without manually fiddling around with the metadata. I have 
 tried this https://github.com/mojaveazure/seurat-disk but it looks unmaintained but most importantly not functional.

How are you trying to convert the data set? Perhaps I need to convert it myself and provide it along the h5ad object.

**Comment by deevdevil88** [comment]
Hi @pati-ni 
I tried SeuratDisk and as you said, it doesnt deal with the Anndata object very well. In the end what worked was zelkoconvertor , by doing it as done here https://github.com/theislab/zellkonverter/issues/60 . I managed to get a singlecellexperiment object which i can convert to a seurat object fro my purposes. I tried sceasy and that dint work and i tried the  zelkoconvertor::readH5AD() function but with the R reader yesterday and that dint work very well either. In the end using the conda eenv way worked. So i think i am ok for now. But if you do create a seurat object please let me know! i want to make sure i have the right conversion.


Thanks,
Devika

**Comment by pati-ni** [comment]
Thanks for the update @deevdevil88. I will close this for now, but feel free to re-open if metadata is not parsed properly and I will make sure to have a look at it
